###############################################################################

# Data-validity checking for data-structures in `dupree`

###############################################################################

.build_name_checker <- function(label) {
  function(x) label %in% names(x)
}

###############################################################################

.has_content <- .build_name_checker("content")

.has_parsed_content <- .build_name_checker("parsed_content")

###############################################################################

#' Checks if a data-structure conforms to the structure generated by
#'   `lintr`s `get_source_expressions` function
#'
#' @param        x             Any data structure
#'
#' @importFrom   purrr         map_lgl
#'
#' @return       Boolean
#'
.is_source_expressions_object <- function(x) {
  # source_expressions structures are generated by
  # lintr::get_source_expressions
  # - should have `expressions`, `error`, `lines` entries
  # - and each `expressions` entry should have a `content` entry
  is.list(x) &&
    all(c("expressions", "error", "lines") %in% names(x)) &&
    all(purrr::map_lgl(x[["expressions"]], .has_content))
}

#' Checks if a data-structure conforms to the structure of a `parsed_content`
#' entry as present in a subentry of get_source_expressions...$expressions
#' `
.is_parsed_content <- function(x) {
  # data-frame with columns: line1, col1, line2, col2, id, parent, token,
  #   terminal, text
  reqd_columns <- c(
    "line1", "col1", "line2", "col2", "id", "parent", "token",
    "terminal", "text"
  )

  is.data.frame(x) &&
    all(reqd_columns %in% colnames(x))
}
